<?xml version="1.0" ?>
<BookCatalog xmlns="http://cs.skuniv.ac.kr/xml/2023/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema=instance"
	xsi:schemaLocation="http://cs.skuniv.ac.kr/xml/2023/ ex4-2.xsd">
	
<!DOCTYPE BookCatalog [
	<!ELEMENT BookCatalog (Book*)>  <!-- 모든요소이므로, *입력 -->
	<!ELEMENT Book (Title, Author, Year)>
	<!ELEMENT Title (#PCDATA)>
	<!ELEMENT Author (#PCDATA)>
	<!ELEMENT Year (#PCDATA)>
]>

<BookCatalog>
	<Book>
		<Title>안네의 일기</Title>
		<Author>안네 프랑크</Author>
		<Year>1940</Year>
	</Book>
</BookCatalog>
